# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - '!main'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Update NPM
        run: npm install -g npm
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: npm run lint
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Update NPM
        run: npm install -g npm
      - name: NPM Install
        run: npm ci
      - name: Build
        run: npm run build
